[package]
name = "omnisus-db-dbf-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
omnisus-db-dbf = { path = "..", default-features = false }

[[bin]]
name = "dbf"
path = "fuzz_targets/dbf.rs"
test = false
doc = false
bench = false


[[bin]]
name = "dbc"
path = "fuzz_targets/dbc.rs"
test = false
doc = false
bench = false
