from typing import Final

import pyarrow as pa

API_VERSION: Final[int]
__version__: str

class UnsupportedDbfError(ValueError): ...
class InvalidDbfError(ValueError): ...

class DbfBatchReader:
    def __iter__(self) -> DbfBatchReader: ...
    def __next__(self) -> pa.RecordBatch: ...
    def close(self) -> None: ...

def open_reader(data: bytes, *, encoding: str, batch_rows: int) -> DbfBatchReader: ...
